### PR TITLE
Updates NSSM set to include application directory update.

### PR DESCRIPTION
**Pull request by kenmaglio**

### CODE REVIEW

**Review by ktreese — COMMENTED** [review]
@kenmaglio I don't think we ported this into the nssm module.  Should this be closed?

**Comment by ktreese** [comment]
@kenmaglio Refer ktreese/nssm#10

**Comment by kenmaglio** [comment]
I'm pretty sure it should include this ability, we thought this was an issue back a while ago, however it ended up not being the case, but it is still an issue/feature which should be fixed.

**Comment by ktreese** [comment]
closing due to age

**Pull request closed without merging**
